# Generated by Django 5.0.7 on 2024-08-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_details', models.CharField(max_length=40)),
                ('vin', models.IntegerField()),
                ('description_details', models.TextField()),
            ],
        ),
    ]
